### ISSUE TITLE
Define new controls with a simple function call 

### ISSUE THREAD

**Issue by karstenj** [tidalcycles/vortex#40]
Post of Alex on discord:
- be able to define new controls with a simple function call (doesn't seem to be the case atm)

**Comment by karstenj** [comment]
A example of such a function from strudel would be fine.

**Comment by karstenj** [comment]
@yaxu have you an example of this one?

**Comment by yaxu** [comment]
@karstenj sure, there is:
```js
var foo = createParam('foo');
```
With a helper function for multiple controls:
```js
var { action, to, part, by, dur, waist, back, head } 
= createParams( 'action', 'to', 'part', 'by', 'waist', 'back', 'head');
```
This adds the control to the pattern class for method chaining, as well as returning the function.

It's defined here:
https://github.com/tidalcycles/strudel/blob/dd51bd0a2ff4bc4e7614467ca092e5ab74d11928/packages/core/controls.mjs#L846-L854
